name: foodgram workflow


on: [push]

jobs:
  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sergrampro/foodgram_project
          tag_with_ref: true

  deploy:
    runs-on: ubuntu-latest
    needs: push_to_docker_hub
    steps: 
      - uses: actions/checkout@master 
      - name: copy docker-compose.yaml file to remote 
        uses: appleboy/scp-action@master 
        with: 
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USER }} 
          key: ${{ secrets.SSH_KEY }} 
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "./docker-compose.yaml, nginx" 
          target: "./" 
      - name: executing remote ssh commands to deploy 
        uses: appleboy/ssh-action@master 
        with: 
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USER }} 
          key: ${{ secrets.SSH_KEY }} 
          passphrase: ${{ secrets.PASSPHRASE }}
          script: | 
            sudo docker pull sergrampro/foodgram_project
            sudo docker-compose stop
            sudo docker-compose rm
            sudo docker-compose up --build -d